### ISSUE TITLE
⛰️[EPIC]: Setting up more pre-commit hooks

### ISSUE THREAD

**Issue by akshaysubr** [NVIDIA/modulus#122]
Having a good suite of pre-commit hooks can help keep the code clean and ease development. We also now use the pre-commit recipes in our CI system. Additionally using pre-commit hooks before any code is pushed can help catch errors at the source reducing the burden on the CI system.

```[tasklist]
### Tasks
- [ ] https://github.com/NVIDIA/modulus/issues/121
- [ ] https://github.com/NVIDIA/modulus/issues/120
- [ ] https://github.com/NVIDIA/modulus/issues/119
- [ ] https://github.com/NVIDIA/modulus/issues/118
- [ ] https://github.com/NVIDIA/modulus/issues/123
- [ ] https://github.com/NVIDIA/modulus/issues/124
- [ ] https://github.com/NVIDIA/modulus/issues/131
- [ ] https://github.com/NVIDIA/modulus/issues/172
```
