### ISSUE TITLE
⛰️[EPIC]: Add support for model weight uncertainty to training routines.

### ISSUE THREAD

**Issue by dallasfoster** [NVIDIA/modulus#209]
Adding support for model weight uncertainty while training is important for users who intend to use an ensemble of models during inference. Most of the utility will come through checkpointing schedules, but there may be additional utilities that can modify the optimization step by incorporating weight/prediction diversity.

```[tasklist]
### Tasks
- [ ] https://github.com/NVIDIA/modulus/issues/210
- [ ] https://github.com/NVIDIA/modulus/issues/211
- [ ] https://github.com/NVIDIA/modulus/issues/212
- [ ] https://github.com/NVIDIA/modulus/issues/213
```
