### ISSUE TITLE
⛰️[EPIC]: CorrDiff integration

### ISSUE THREAD

**Issue by mnabian** [NVIDIA/modulus#228]
Placeholder for tracking the issues related to integrating the ResDiff model

```[tasklist]
### Integration Tasks
- [x] Use Modulus Docker image for ResDiff (https://github.com/NVIDIA/modulus/pull/266)
- [x] Compare the results generated with stochastic and deterministic samplers (https://github.com/NVIDIA/modulus/pull/260)
- [x] Use Modulus logging utilities (https://github.com/NVIDIA/modulus/pull/251)
- [x] Use Modulus distributed utilities (https://github.com/NVIDIA/modulus/pull/247)
- [x] Use Modulus checkpointing (https://github.com/NVIDIA/modulus/pull/282)
- [x] Use hydra configs (https://github.com/NVIDIA/modulus/pull/268)
- [x] Package and import the stochastic sampler (https://github.com/NVIDIA/modulus/pull/250)
- [x] Add profiling markers (https://github.com/NVIDIA/modulus/pull/306)
- [x] Black formatting (https://github.com/NVIDIA/modulus/pull/257)
- [x] Linting (https://github.com/NVIDIA/modulus/pull/262)
- [x] Code cleanup (https://github.com/NVIDIA/modulus/pull/262, https://github.com/NVIDIA/modulus/pull/274)
- [x] Remove dependency to `pickle` due to security issues
- [x] Remove the `persistance` decorator (https://github.com/NVIDIA/modulus/pull/274)
- [x] Update README (https://github.com/NVIDIA/modulus/pull/288)
- [x] Unit tests (https://github.com/NVIDIA/modulus/pull/281)
- [x] Docstrings (https://github.com/NVIDIA/modulus/pull/274)
- [x] Move files out of `experimental` (https://github.com/NVIDIA/modulus/pull/274)
```
```[tasklist]
### Issues
- [x] 'distributed.py' has to be removed but that breaks loading the existing checkpoints (https://github.com/NVIDIA/modulus/pull/274)
```

```[tasklist]
### Performance Optimization
- [x] Add support for CUDA Graphs (will not do)
- [x] Support for fp16 in inference (https://github.com/NVIDIA/modulus/pull/288)
- [x] Enable multi-GPU inference (https://github.com/NVIDIA/modulus/pull/281)
- [x] Enable batch_size > 1 for inference (https://github.com/NVIDIA/modulus/pull/281)
```

```[tasklist]
### Logging enhancement
- [x] Add W&B logging (https://github.com/NVIDIA/modulus/pull/316)
```

```[tasklist]
### Dataset
- [x] Get permission to publish the CWA dataset
- [x] Trim the Zarr dataset to include only the four target variables
- [x] Publish the dataset on NGC (https://github.com/NVIDIA/modulus/pull/330)
```

```[tasklist]
### Validation
- [x] Verify CorrDiff runs on multiple nodes
```

**Comment by jleinonen** [comment]
I'm gathering here the suggestions from our discussion:

### Code structuring
- [ ] Split `generate.py`, `train.py` and `training_loop.py` into functions/classes that handle more well-defined tasks
- [ ] Reduce redundancy between the above files
- [ ] Clean up handling of config files
- [ ] Specify clearly in an interface what interface data loaders need to follow, to facilitate adding new loaders
- [ ] Same as above, but for models (e.g. U-Nets)
- [ ] Interoperability with diagnostic model code base (TBA)

### Optimizations
- [ ] AMP support
- [ ] Support distributing generation over time steps as well as ensemble members

**Comment by mnabian** [comment]
Moving these suggested items to a new epic for CorrDiff enhancements: https://github.com/NVIDIA/modulus/issues/353

**Comment by mnabian** [comment]
Epic Completed!
