### ISSUE TITLE
⛰️[EPIC]: FIGConvNet integration for aerodynamic evaluation

### ISSUE THREAD

**Issue by mnabian** [NVIDIA/modulus#354]
```[tasklist]
### Integration
- [x] Integration of the TPUN
- [x] Enable Hydra config
- [ ] Add docstrings
- [ ] Add license headers
- [ ] Add README
- [ ] Use Modulus Distributed Manager
- [ ] Use Modulus checkpointing
- [ ] Use Modulus logging
```

```[tasklist]
### Verification
- [ ] Verify on the DrivAER dataset
- [ ] Verify on the Ahmed body dataset
```

```[tasklist]
### Optimization
- [ ] Enable AMP
- [ ] Enable Tensor Core compute
- [ ] Enable CUDA Graphs
- [ ] Enable JIT compilation
- [ ] Profile the code and identify the bottlenecks
- [ ] Other performance optimizations identified in profiles
```

```[tasklist]
### Maintenance
- [ ] Develop unit tests
- [ ] Perform QA
```

**Comment by ram-cherukuri** [comment]
@mnabian What we please add the details to the scope of this epic?

**Comment by mnabian** [comment]
@Alexey-Kamenev do you have another epic for  FigConvNet integration? If so, we can close this one as duplicate.

**Comment by Alexey-Kamenev** [comment]
No, that's the only one. I will rename it to use FIGConvNet instead of TPUN (that's the old name).
