### ISSUE TITLE
⛰️[EPIC]: Fast Neighbor List

### ISSUE THREAD

**Issue by mnabian** [NVIDIA/modulus#359]
```[tasklist]
### Tasks
- [x] Compare fast neighbor list routines (Open3D, RAFT, PySDF)
- [x] https://github.com/NVIDIA/modulus/issues/369
- [x] Documentation of the Modulus neighbor list
- [x] Develop unit tests for the Modulus neighbor list
- [x] https://github.com/NVIDIA/modulus/issues/370
```

**Comment by mnabian** [comment]
PR: https://github.com/NVIDIA/modulus/pull/368
