### ISSUE TITLE
⛰️[EPIC]: Graph Transformers

### ISSUE THREAD

**Issue by mnabian** [NVIDIA/modulus#360]
```[tasklist]
### Tasks
- [x] Implement a graph transformer model in Modulus
- [x] Graph transformer documentation
- [x] Graph transformer example
- [x] Graph transformer unit tests
```

**Comment by mnabian** [comment]
Added in this PR: https://github.com/NVIDIA/modulus/pull/583
