### ISSUE TITLE
⛰️[EPIC]: 3D UNet

### ISSUE THREAD

**Issue by mnabian** [NVIDIA/modulus#463]
```[tasklist]
### Tasks
- [ ] https://github.com/NVIDIA/modulus/issues/464
- [ ] https://github.com/NVIDIA/modulus/issues/465
- [ ] https://github.com/NVIDIA/modulus/issues/466
- [ ] https://github.com/NVIDIA/modulus/issues/467
- [ ] https://github.com/NVIDIA/modulus/issues/512
```

**Comment by mnabian** [comment]
https://github.com/NVIDIA/modulus/pull/496
