### ISSUE TITLE
⛰️[EPIC]: Mesh Processing Utilities for Graph Models

### ISSUE THREAD

**Issue by mnabian** [NVIDIA/modulus#498]
```[tasklist]
### Converters
- [x] OBJ to VTP
- [x] VTP to STL
- [x] Multiple VTP files to a single VTP file
```

```[tasklist]
### Mesh manipulation
- [x] Convert mixed mesh to tet mesh
```

**Comment by mnabian** [comment]
Implemented in this PR: https://github.com/NVIDIA/modulus/pull/495
