### ISSUE TITLE
⛰️[EPIC]: Generalized DALI dataloader for VTK

### ISSUE THREAD

**Issue by mnabian** [NVIDIA/modulus#500]
```[tasklist]
### P0 - Must have
- [x] Support for VTP
- [x] Support for VTU
- [x] Support for Normalization
- [ ] https://github.com/NVIDIA/modulus/issues/557
```
