### ISSUE TITLE
⛰️[EPIC]: CorrDiff Usability Enhancements

### ISSUE THREAD

**Issue by mnabian** [NVIDIA/modulus#589]
```[tasklist]
### Tasks - P0
- [ ] https://github.com/NVIDIA/modulus/issues/639
- [ ] https://github.com/NVIDIA/modulus/issues/633
- [ ] https://github.com/NVIDIA/modulus/issues/632
- [ ] https://github.com/NVIDIA/modulus/issues/614
- [ ] https://github.com/NVIDIA/modulus/issues/613
- [ ] CorrDiff: Generalized dataloader
- [ ] https://github.com/NVIDIA/modulus/issues/612
- [ ] CorDiff: Unit tests for training/inference, put it in the examples folder
- [ ] https://github.com/NVIDIA/modulus/issues/601
- [ ] https://github.com/NVIDIA/modulus/issues/611
- [ ] https://github.com/NVIDIA/modulus/issues/600
- [ ] https://github.com/NVIDIA/modulus/issues/599
- [ ] https://github.com/NVIDIA/modulus/issues/634
- [ ] https://github.com/NVIDIA/modulus/pull/594
- [ ] https://github.com/NVIDIA/modulus/issues/541
- [ ] https://github.com/NVIDIA/modulus/issues/537
- [ ] https://github.com/NVIDIA/modulus/issues/313
- [ ] https://github.com/NVIDIA/modulus/issues/542
- [ ] https://github.com/NVIDIA/modulus/issues/415
- [ ] https://github.com/NVIDIA/modulus/issues/655
```

```[tasklist]
### Tasks - P1
- [x] https://github.com/NVIDIA/modulus/issues/598
- [ ] CorrDiff: Support distributing generation over time steps as well as ensemble members
- [ ] https://github.com/NVIDIA/modulus/issues/602
- [ ] https://github.com/NVIDIA/modulus/issues/635
- [ ] https://github.com/NVIDIA/modulus/issues/623
- [ ] CorrDiff: Avoid hard-coding the validation year in the datapipe
- [ ] https://github.com/NVIDIA/modulus/issues/622
- [ ] https://github.com/NVIDIA/modulus/issues/478
```

**Comment by ram-cherukuri** [comment]
@mnabian So looking through the task list, we are rearchitecting the code to make it cleaner. From a user perspective, what will they be able to do more easily in terms of say what types of data formats can they ingest, does our training code provide configs that make it easy to train with the supported data formats?

**Comment by mnabian** [comment]
[Placeholder] Scope of the enhancements:

- Configs:
- Training:
- Inference:
- Dataloader:
- Documentation:
- Visualization:

**Comment by mnabian** [comment]
Closing as complete.

https://github.com/NVIDIA/modulus/pull/604
https://github.com/NVIDIA/modulus/pull/629
https://github.com/NVIDIA/modulus/pull/636
https://github.com/NVIDIA/modulus/pull/676
